remote_theme: just-the-docs/just-the-docs
title: 'LSE MY457: Causal Inference for Observational and Experimental Studies'
description: 'Course Website for Winter Term 2024'
show_downloads: false

plugins:
  - jekyll-default-layout

